[package]
name = "apivolve"
version = "0.1.0"
description = "Apivolve is an API evolution tool, it helps keep your APIs backwards compatible yet clean, and generates client/server code in a variety of languages."
edition = "2021"
publish = true
license = "Apache-2.0"
default-run = "apivolve"

[[bin]]
name = "apivolve"
path = "src/main.rs"

[[bin]]
name = "apivolve-gen-json"
path = "src/gen/json/main.rs"

[lib]
name = "apivolve"
path = "src/lib.rs"

[features]
jemalloc = ["jemallocator"]

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
log = "0.4"
env_logger = "0.9"
structopt = { version = "0.3" }
lalrpop-util = { version = "0.19.6", features = ["lexer"] }
regex = "1.5.4"
lazy_static = "1.4.0"
sha2 = "0.9.8"
base64 = "0.13.0"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.3", optional = true }

[profile.release]
lto = "thin"
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

