[package]
name = "apivolve"
version = "0.1.0"
edition = "2021"
publish = true

[[bin]]
name = "apivolve"
path = "src/main.rs"

[lib]
name = "apivolve"
path = "src/lib.rs"

[features]
jemalloc = ["jemallocator"]

[build-dependencies]
lalrpop = "0.19.6"

[dependencies]
log = "0.4"
env_logger = "0.9"
structopt = { version = "0.3" }
lalrpop-util = { version = "0.19.6", features = ["lexer"] }
regex = "1.5.4"
lazy_static = "1.4.0"
twox-hash = "1.6.1"
base64 = "*"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { version = "0.3", optional = true }

[profile.release]
lto = "thin"
opt-level = 3

[profile.dev.package."*"]
opt-level = 3

