
name: 'Tests'

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  checks:
    name: Build, tests, lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get tag
        id: tag
        run: echo "::set-output name=tag::${GITHUB_REF##*/}_$(date +'%Y-%m-%d')_${{ github.run_number }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          context: .
          push: false
          tags: mverleg/apivolve:${{ steps.tag.outputs.tag }},mverleg/apivolve:latest

